services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
    networks:
      - mongodb-network
    volumes:
      - polls_mongodb_data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    ports:
      - '8081:8081'
    networks:
      - mongodb-network
    volumes:
      - polls_mongo_express_data:/data/db
    depends_on:
      - mongodb

networks:
  mongodb-network:
    driver: bridge